# Generated by Django 6.0 on 2026-01-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to='core.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='core.trainer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
