# Generated by Django 6.0 on 2026-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
    ]
