# Generated by Django 6.0 on 2026-01-02 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_is_read_alter_chatmessage_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
