# Generated by Django 6.0 on 2026-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberachievement',
            name='achievement_slug',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
