from django.db import migrations, models, connection

def convert_uuid_to_bigint(apps, schema_editor):
    with connection.cursor() as cursor:
        # 1. Find and drop all foreign keys in gym app
        cursor.execute("""
            SELECT conname, relname 
            FROM pg_constraint c 
            JOIN pg_class r ON c.conrelid = r.oid 
            WHERE r.relname LIKE 'gym_%' AND contype = 'f'
        """)
        constraints = cursor.fetchall()
        for con, table in constraints:
            cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{con}"')

        # 2. Define tables and their ID/FK columns to convert
        # We also include columns from other tables that point to these
        tables_to_convert = [
            ('gym_trainer', ['id', 'user_id']),
            ('gym_member', ['id', 'user_id', 'assigned_trainer_id']),
            ('gym_subscriptionplan', ['id']),
            ('gym_membersubscription', ['id', 'member_id', 'plan_id']),
            ('gym_payment', ['id', 'subscription_id']),
            ('gym_program', ['id', 'created_by_id']),
            ('gym_program_assigned_members', ['id', 'program_id', 'member_id']),
            ('gym_workoutday', ['id', 'program_id']),
            ('gym_exercise', ['id']),
            ('gym_workoutset', ['id', 'workout_day_id', 'exercise_id']),
            ('gym_attendancerecord', ['id', 'member_id']),
            ('gym_progressentry', ['id', 'member_id', 'recorded_by_id']),
            ('gym_message', ['id', 'recipient_id', 'created_by_id'])
        ]

        # 3. Convert columns
        for table, columns in tables_to_convert:
            for col in columns:
                cursor.execute(f"""
                    SELECT data_type 
                    FROM information_schema.columns 
                    WHERE table_name = '{table}' AND column_name = '{col}'
                """)
                res = cursor.fetchone()
                if res and res[0] == 'uuid':
                    # Convert UUID to BigInt. 
                    cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" TYPE bigint USING (random()*1000000000)::bigint')
                elif res and res[0] == 'integer':
                    cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" TYPE bigint')

        # 4. Add IDENTITY to primary keys
        for table, columns in tables_to_convert:
            if 'id' in columns:
                cursor.execute(f"SELECT is_identity FROM information_schema.columns WHERE table_name = '{table}' AND column_name = 'id'")
                res = cursor.fetchone()
                if res and res[0] == 'NO':
                    # Only add if not already an identity
                    cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY')

class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_uuid_to_bigint, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='attendancerecord',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='exercise',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='member',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='membersubscription',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='message',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payment',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='program',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='progressentry',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='subscriptionplan',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='trainer',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='workoutday',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='workoutset',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ]
        )
    ]
