# Generated by Django 6.0 on 2026-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_fix_id_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gym_name', models.CharField(default='Gym Flow', max_length=200)),
                ('address', models.TextField(default='123 Fitness Blvd, Workout City')),
                ('phone', models.CharField(default='+1 234 567 8900', max_length=20)),
                ('email', models.EmailField(default='contact@gymflow.com', max_length=254)),
                ('notify_new_member', models.BooleanField(default=True)),
                ('notify_payment_alerts', models.BooleanField(default=True)),
                ('notify_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
