# Generated by Django 6.0 on 2026-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_conversation_trainer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
