# Generated by Django 6.0 on 2026-01-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='gym.member'),
        ),
    ]
